name: CI

on: [ push ]
jobs:
  ci:
    runs-on: docker
    strategy:
      matrix:
        python-version: ['3.10', '3.13']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - run: pip install -r requirements-dev.txt

      - run: pylint --fail-under=9.0 --max-line-length=120 netbox_pve_sync

      - run: pytest -q
