export const time = new Date(Date.now() - 600000).toISOString();
export const runId = "11111111-1111-4111-8111-111111111111";
export const source = (i = 1) => ({
  source_instance: "source-" + i,
  type: i % 2 ? "proxmox" : "esxi",
  name: "Source " + String(i).padStart(3, "0"),
  address: "host-" + i + ".example.test",
  enabled: i !== 2,
  sync_enabled: i !== 3,
  verify_ssl: true,
  sync_interval_seconds: 600,
  site_slug: i % 2 ? "dc1" : "dc2",
  cluster_name: "Cluster " + i,
  platform_slug: "linux",
  device_role_slug: "server",
  device_type_slug: "server",
  cluster_type_slug: "cluster",
  legacy_identity_owner: false,
  status: i === 2 ? "disabled" : i === 3 ? "sync_disabled" : "enabled",
});
export const run = (status = "SUCCEEDED") => ({
  run_id: runId,
  source_instance: "source-1",
  source_type: "proxmox",
  trigger: "manual",
  status,
  started_at: time,
  finished_at: status === "RUNNING" ? null : time,
  duration_ms: status === "RUNNING" ? null : 8100,
  plan_digest: null,
  planner_version: null,
  actions: {
    create: 1,
    update: 2,
    no_change: 0,
    review_required: 0,
    blocked: 0,
    ignored: 0,
    unsupported: 0,
    retain_only: 0,
  },
  error_code: null,
  error_message_safe: null,
  created_by: "web/manual",
});
export function diagnostics(sources = [source()]) {
  const component = {
    status: "HEALTHY",
    checked_at: time,
    safe_code: null,
    safe_message: null,
    last_seen_at: time,
    last_success_at: time,
    next_expected_at: null,
  };
  return {
    overall_status: "HEALTHY",
    generated_at: time,
    components: Object.fromEntries(
      [
        "api",
        "registry",
        "run_history",
        "discovery_worker",
        "apply_worker",
        "scheduler",
      ].map((key) => [key, { ...component }]),
    ),
    sources: sources.map((s) => ({
      source_instance: s.source_instance,
      source_type: s.type,
      enabled: s.enabled,
      sync_enabled: s.sync_enabled,
      sync_interval_seconds: 600,
      status: s.enabled ? "HEALTHY" : "UNKNOWN",
      latest_run: {
        run_id: runId,
        trigger: "manual",
        status: "SUCCEEDED",
        started_at: time,
        finished_at: time,
      },
      latest_success_at: time,
      latest_scheduled_run: null,
      latest_manual_run: null,
      scheduler_state: s.enabled && s.sync_enabled ? "WAITING" : "DISABLED",
      last_scheduled_run_at: null,
      next_expected_at: s.enabled && s.sync_enabled ? time : null,
      warning_count: 0,
      warnings: [],
    })),
    stale_runs: [],
    warnings: [],
  };
}
export const staleWarning = {
  warning_code: "STALE_RUNNING",
  safe_message: "Completion not confirmed",
  source_instance: "source-1",
  source_type: "proxmox",
  trigger: "manual",
  run_id: runId,
  started_at: time,
  age_seconds: 10000,
};
